apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-state-management
  namespace: nifi
data:
  state-management.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <state-management>
      <local-provider>
        <id>local-provider</id>
        <class>org.apache.nifi.controller.state.providers.local.WriteAheadLocalStateProvider</class>
        <property name="Directory">./state/local</property>
      </local-provider>
      <cluster-provider>
        <id>zk-provider</id>
        <class>org.apache.nifi.controller.state.providers.zookeeper.ZooKeeperStateProvider</class>
        <property name="Connect String">zookeeper:2181</property>
        <property name="Root Node">/nifi</property>
        <property name="Session Timeout">30 seconds</property>
        <property name="Access Control">Open</property>
      </cluster-provider>
    </state-management>

