apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
  labels:
    app: nifi
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443
    - name: cluster
      port: 11443
      targetPort: 11443
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-ui
  namespace: nifi
spec:
  type: LoadBalancer
  selector:
    app: nifi
  ports:
    - name: https
      port: 8443
      targetPort: 8443

